notifications:
    email: false

sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y beanstalkd cpanminus
    - sudo cpanm Test::Nginx

cache:
  directories:
  - download-cache

env:
  global:
    - JOBS=3
    - TEST_NGINX_SLEEP=0.5
  matrix:
    - OR_VERSION=1.11.2.2

services:
 - beanstalkd

install:
  - if [ ! -f download-cache/openresty-$OR_VERSION.tar.gz ]; then wget -P download-cache http://openresty.org/download/openresty-$OR_VERSION.tar.gz; fi

script:
  - tar -xvf download-cache/openresty-$OR_VERSION.tar.gz
  - cd openresty-$OR_VERSION/
  - ./configure -j2 --prefix=/usr/local/openresty
  - make -j2
  - sudo make install
  - cd ..
  - export PATH=/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin:$PATH
  - nginx -V
  - prove -r t
